# rundeck-ansible 

version: '3'

services:

    rundeck:
        build:
            context: .
        container_name: rundeck
        hostname: rundeck
        restart: on-failure:5
        links:
            - mariadb
        depends_on:
            - mariadb
        env_file:
            .env
        ports:
            - 4440:4440
            - 8080:8080
        volumes:
            - ansible-data:/home/rundeck/ansible
            - rundeck-data:/home/rundeck/server/data
        networks:
            - db-net
    mariadb:
        image: mariadb:10.5.8
        container_name: mariadb
        restart: on-failure:5
        env_file:
            .env
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - db-net
volumes:
  mariadb-data:
  ansible-data:
  rundeck-data:
networks:
  db-net:
